1.public class Divisiblebyzero{
    public static void main(String []args){
        try{
            int numerator = 10;
            int denominator = 0;
            
            int result = numerator/denominator;
            System.out.println("Result:"+result);
        }
        catch(ArithmeticException e){
            System.out.println("Division by zero is not allowed"+e.getMessage());
        }
        finally{
            System.out.println("Finally black is always excuted");
        }
    }
}

2.public class TryCatchExample {
  public static void main(String[] args) {
    try {
      int x = 5 / 0; 
      System.out.println("Result: " + x);
    } catch (ArithmeticException e) {
      System.out.println("Error: Cannot divide by zero!");
      System.out.println("Exception message: " + e.getMessage());
    } catch (Exception e) {
      System.out.println("Error: An unexpected error occurred.");
      System.out.println("Exception message: " + e.getMessage());
    } finally {
      System.out.println("Finally block executed.");
    }
  }
}

3.public class ExceptionHandlingExample {
    public static void main(String[] args) {
        try {
            int x = 5 / 0; 
        } catch (ArithmeticException e) {
            System.out.println("Error: Cannot divide by zero!");
        } finally {
            System.out.println("Finally block executed");
        }
    }
}
